- hosts: foo-staging
  roles:
    - role: ansible-role-conjur
      conjur_account: cucumber
      conjur_appliance_url: "http://conjur:3000"
      conjur_host_factory_token: "{{lookup('env', 'STAGING_HFTOKEN')}}"
      conjur_host_name: "conjur_{{ ansible_hostname }}"

  tasks:
    - name: Find current running Application process
      shell: pgrep ruby || true
      register: current_application_process

    - name: Stop application server (if running)
      shell: kill -9 {{current_application_process.stdout}}
      when: current_application_process.stdout != ''

    - name: Start application with secrets from Conjur
      conjur:
        variables:
          DB_USERNAME: staging/myapp/database/username
          DB_PASSWORD: staging/myapp/database/password
          STRIPE_API_KEY: staging/myapp/stripe/private_key
        command: rackup -p 4567 --host 0.0.0.0 -D
